name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_group: [unit, widget, integration]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run ${{ matrix.test_group }} tests with xvfb
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb
          if [[ "${{ matrix.test_group }}" == "integration" ]]; then
            xvfb-run --auto-servernum -- flutter test integration_test
          else
            xvfb-run --auto-servernum -- flutter test --tags ${{ matrix.test_group }}
          fi
